apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- clusterstoragecontainer.yaml
images:
- name: quay.io/opendatahub/model-registry-storage-initializer
  newName: quay.io/opendatahub/model-registry-storage-initializer
  newTag: v0.2.12
